# Generated by Django 4.2.6 on 2023-11-02 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_last_login_usermodel_date_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='Otp_Num',
            new_name='Otp',
        ),
    ]
