# Generated by Django 4.2.6 on 2023-11-02 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_otp_num_usermodel_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='Otp',
            new_name='Otp_Num',
        ),
    ]
